sudo: false  # Use container-based infrastructure
language: python
python:
  - "2.7"
  - "3.6"
git:
  # don't need the default depth of 50
  # but don't want to use a depth of 1 since that affects
  # whether jobs run when you have multiple commits queued
  # https://github.com/travis-ci/travis-ci/issues/4575
  depth: 10
cache:
  pip: true
  # cache directory used for Ensembl downloads of GTF and FASTA files
  # along with the indexed db of intervals and ID mappings and pickles
  # of sequence dictionaries. Also, pip
  directories:
    - $HOME/.cache/pyensembl/
    - $HOME/.cache/pyensembl/GRCh37/ensembl75/
    - $HOME/.cache/pyensembl/GRCh38/ensembl81/
    - $HOME/.cache/pyensembl/GRCh38/ensembl87/
    - $HOME/miniconda
before_install:
  # don't install miniconda if it's already cached
  # if not yet installed, use different versions for py2 vs. py3
  - |
    if [ -d  $HOME/miniconda/bin ];
      then
      echo "miniconda already installed"
    else
      rm -rf $HOME/miniconda
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
    fi
  # reset the shell's lookup table for program name to path mappings
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - python --version
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy nose pandas pandoc
  - source activate test-environment
  - conda install -c conda-forge pypandoc
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls
script:
  # run pylint
  - ./lint.sh
  # install older human Ensembl releases needed for tests
  - pyensembl install --release 75 --species human
  - pyensembl install --release 81 --species human
  # install latest human & mouse Ensembl releases
  - pyensembl install --release 87 --species human
  - pyensembl install --release 87 --species mouse
  # now actually run the tests, generate a coverage report and run linter
  - nosetests test --with-coverage --cover-package=varcode
after_success:
  coveralls
deploy:
  provider: pypi
  user: openvax
  password:
    secure: "FpDbTEuGN2NGKoSMcD4A8bVvAv1TKhALqZymnjWPfFxy1AvOcRQb2k4tornLjONgccLjw+Uq7Jh66Pv8D9nK8h7AY3Sx9hmip7lSWgIraguWdTvumXfAKIJ+CH+PNRjH9qXBkrdExYBNbF0Mb3XyTmpRU02FEDxNzOJcBS+wokQ="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
